FEDX-44 : Update to null safety
Workiva/opentracing_dart pull request #57
Opened 2023-06-02 16:14 UTC by alishadalal-wk

## Summary

Migrate to null safety. Run the null safety migration tool with Dart migrate and check/adjust its suggestions if needed.
Apply the migration, and fix any static errors. Do a dart format, run the tests, fixing any issues.

2023-06-02 16:16 UTC, aviary3-wk commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2023-06-09 18:26 UTC, dustinlessard-wf approved these changes

2023-06-09 18:28 UTC, dustinlessard-wf commented on example/json_serializable_span.dart
> +    fieldMap[traceIdField] = span.context.traceId;
Hmmm... Can't span or context still be null?

2023-06-09 18:28 UTC, dustinlessard-wf requested changes
Need to clarify something first.

2023-06-09 18:34 UTC, dustinlessard-wf approved these changes

2023-06-22 20:22 UTC, robbecker-wf commented
+10 @Workiva/release-management-p

2023-06-22 20:22 UTC, rmconsole-wf approved these changes
+1 from RM

2023-06-22 20:22 UTC, merged